---
collections:
  - name: ansible.windows
    version: 1.12.0
  - name: community.docker
    version: 3.2.0
  - name: community.windows
    version: 1.11.1

roles:
  - src: https://github.com/Ableton/ansible-role-pkg-mgr-path
    scm: git
    name: ableton.pkg_mgr_path
    version: 0.0.2
