---
collections:
  - name: ansible.windows
    version: 3.3.0
  - name: community.windows
    version: 3.1.0

roles:
  - src: https://github.com/Ableton/ansible-role-pkg-mgr-path
    scm: git
    name: ableton.pkg_mgr_path
    version: 0.0.3
