---
# Shutdown the service first
- ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}/shutdown.yml"

- ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}/disable-service.yml"
