---
- name: Sanity check required variables
  assert:
    that:
      - jenkins_config_group != ''
      - jenkins_config_owner != ''
      - jenkins_master_url != ''
      - jenkins_swarm_home != ''
    quiet: true
