---
- name: Include platform-specific defaults
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Get UID for jenkins_config_owner user
  ansible.builtin.command: "id -u {{ jenkins_config_owner }}"
  changed_when: false
  register: uid

- name: Get list of disabled services
  ansible.builtin.command: "launchctl print-disabled gui/{{ uid.stdout }}"
  changed_when: false
  register: disabled_services

- name: Enable launchctl service (pre-Ventura)
  ansible.builtin.command: >
    launchctl enable gui/{{ uid.stdout }}/{{ jenkins_swarm_client_ident }}
  changed_when: true
  when:
    - ansible_distribution_major_version | int < 13
    - jenkins_swarm_client_disabled_pre_ventura in disabled_services.stdout_lines

- name: Enable launchctl service (post-Ventura)
  ansible.builtin.command: >
    launchctl enable gui/{{ uid.stdout }}/{{ jenkins_swarm_client_ident }}
  changed_when: true
  when:
    - ansible_distribution_major_version | int >= 13
    - jenkins_swarm_client_disabled_post_ventura in disabled_services.stdout_lines
