---
- name: Install homebrew dependencies
  homebrew:
    name: "{{ item.key }}"
    state: present
  with_dict: "{{ jenkins_node_packages }}"

# Python 3.x is required for older versions of macOS to work around SSL errors.
- name: Ensure python3 is installed
  homebrew:
    name: "python"
    state: present
  when: >
    ansible_os_family == "Darwin" and
    ansible_distribution_version is version_compare('10.13', '<')

- name: Run installation tasks common to Unix-like systems
  include_tasks: "{{ role_path }}/tasks/unix/install.yml"

- name: Initialize jenkins_swarm_cmd_arguments fact
  set_fact:
    jenkins_swarm_cmd_arguments: ""

- name: Build plist program arguments
  set_fact:
    jenkins_swarm_cmd_arguments: >
      {{ jenkins_swarm_cmd_arguments }}
      <string>{{ jenkins_swarm_cmd_item }}</string>
  with_items: "{{ jenkins_swarm_cmd }}"
  loop_control:
    loop_var: jenkins_swarm_cmd_item

- name: Ensure LaunchDaemon plist file exists
  become: true
  template:
    src: "{{ role_path }}/files/{{ jenkins_swarm_client_ident }}.plist.j2"
    dest: "{{ jenkins_swarm_daemon_plist }}"
