---
- name: Run installation tasks common to Unix-like systems
  ansible.builtin.include_tasks: "unix/install.yml"

- name: Initialize jenkins_swarm_launchd_args fact
  ansible.builtin.set_fact:
    jenkins_swarm_launchd_args: "<string>{{ java_exe }}</string>"

- name: Build plist program arguments
  ansible.builtin.set_fact:
    jenkins_swarm_launchd_args: >
      {{ jenkins_swarm_launchd_args }}
      <string>{{ jenkins_swarm_cmd_item }}</string>
  loop: "{{ jenkins_swarm_launch_args }}"
  loop_control:
    loop_var: jenkins_swarm_cmd_item

- name: Set fact for jenkins_swarm_client_legacy_launchd_plist
  ansible.builtin.set_fact:
    jenkins_swarm_client_legacy_launchd_plist: >-
      /Library/LaunchAgents/{{ jenkins_swarm_client_ident }}.plist
  when: "jenkins_config_owner == 'root'"

- name: See if legacy Swarm Client launchd plist file exists
  ansible.builtin.stat:
    path: "{{ jenkins_swarm_client_legacy_launchd_plist }}"
  register: jenkins_swarm_client_legacy_launchd_plist_file
  when: jenkins_swarm_client_legacy_launchd_plist is defined

- name: Override jenkins_swarm_client_log_dir for non-root installation
  ansible.builtin.set_fact:
    jenkins_swarm_client_log_dir: >-
      /Users/{{ jenkins_config_owner }}/Library/Logs/{{ jenkins_swarm_client_ident }}
  when: "jenkins_config_owner != 'root'"

- name: Ensure that log directory exists
  become: "{{ 'true' if jenkins_config_owner == 'root' else 'false' }}"
  ansible.builtin.file:
    path: "{{ jenkins_swarm_client_log_dir }}"
    state: directory
    mode: "0755"

- name: Unload and remove legacy Swarm Client launchd service
  when:
    - jenkins_swarm_client_legacy_launchd_plist is defined
    - jenkins_swarm_client_legacy_launchd_plist_file.stat.exists
  block:
    - name: Unload legacy Swarm Client service
      become: true
      ansible.builtin.command: >
        launchctl bootout gui/{{ uid.stdout }}
        {{ jenkins_swarm_client_legacy_launchd_plist }}
      changed_when: true
      # The service doesn't necessarily have to be running
      ignore_errors: true  # noqa ignore-errors

    - name: Remove legacy Swarm Client launchd plist file
      become: true
      ansible.builtin.file:
        path: "{{ jenkins_swarm_client_legacy_launchd_plist_file }}"
        state: absent

- name: Set jenkins_swarm_client_launchd_plist fact
  ansible.builtin.include_tasks: "set-launchd-plist.yml"

- name: Ensure Swarm Client launchd plist file exists
  become: true
  ansible.builtin.template:
    src: "{{ jenkins_swarm_client_ident }}.plist.j2"
    dest: "{{ jenkins_swarm_client_launchd_plist }}"
    mode: "0644"
    validate: "plutil -lint %s"
