---
- name: Install homebrew dependencies
  homebrew:
    name: "{{ item.key }}"
    state: present
  with_dict: "{{ jenkins_node_packages }}"

- name: Run installation tasks common to Unix-like systems
  include_tasks: "{{ role_path }}/tasks/unix/install.yml"

- set_fact:
    jenkins_swarm_cmd_arguments: ""

- name: Build plist program arguments
  set_fact:
    jenkins_swarm_cmd_arguments: >
      {{ jenkins_swarm_cmd_arguments }}
      <string>{{ jenkins_swarm_cmd_item }}</string>
  with_items: "{{ jenkins_swarm_cmd }}"
  loop_control:
    loop_var: jenkins_swarm_cmd_item

- name: Ensure LaunchDaemon plist file exists
  become: true
  template:
    src: "{{ role_path }}/files/{{ jenkins_swarm_client_ident }}.plist.j2"
    dest: "{{ jenkins_swarm_daemon_plist }}"
