---
- name: Run installation tasks common to Unix-like systems
  ansible.builtin.include_tasks: "unix/install.yml"

- name: Initialize jenkins_swarm_launchd_args fact
  ansible.builtin.set_fact:
    jenkins_swarm_launchd_args: "<string>{{ java_exe }}</string>"

- name: Build plist program arguments
  ansible.builtin.set_fact:
    jenkins_swarm_launchd_args: >
      {{ jenkins_swarm_launchd_args }}
      <string>{{ jenkins_swarm_cmd_item }}</string>
  with_items: "{{ jenkins_swarm_launch_args }}"
  loop_control:
    loop_var: jenkins_swarm_cmd_item

- name: Ensure LaunchDaemon plist file exists
  become: true
  ansible.builtin.template:
    src: "{{ jenkins_swarm_client_ident }}.plist.j2"
    dest: "{{ jenkins_swarm_daemon_plist }}"
    mode: "0644"
    validate: "plutil -lint %s"
