---
- name: Install homebrew dependencies
  action: homebrew name={{item}} state=present
  with_items: "{{ jenkins_node_packages }}"

- name: Run installation tasks common to Unix-like systems
  include: "{{ role_path }}/tasks/unix/install.yml"

- name: Create Jenkins swarm client launcher script
  copy:
    dest: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
    mode: 0755
    content: |
      #!/bin/sh
      {{ jenkins_swarm_cmd }} &
