---
- name: Run installation tasks common to Unix-like systems
  include_tasks: "unix/install.yml"

- name: Initialize jenkins_swarm_cmd_arguments fact
  set_fact:
    jenkins_swarm_cmd_arguments: "<string>{{ java_exe }}</string>"

- name: Assemble full command arguments
  set_fact:
    jenkins_swarm_full_args: "{{ jenkins_swarm_args + jenkins_swarm_extra_args }}"

- name: Build plist program arguments
  set_fact:
    jenkins_swarm_cmd_arguments: >
      {{ jenkins_swarm_cmd_arguments }}
      <string>{{ jenkins_swarm_cmd_item }}</string>
  with_items: "{{ jenkins_swarm_full_args }}"
  loop_control:
    loop_var: jenkins_swarm_cmd_item

- name: Ensure LaunchDaemon plist file exists
  become: true
  template:
    src: "{{ jenkins_swarm_client_ident }}.plist.j2"
    dest: "{{ jenkins_swarm_daemon_plist }}"
    mode: "0644"
