---
- name: Converge
  hosts: all
  vars:
    jenkins_config_group: "jgroup"
    jenkins_config_owner: "juser"
    jenkins_controller_url: "http://127.0.0.1:8080"
    jenkins_node_name: "molecule-test-node"
    jenkins_swarm_config_args:
      environmentVariables:
        FOO: "BAR"
      labels:
        - "node-label"
        - "extra-label"
    jenkins_swarm_home: "/jenkins"
  roles:
    - role: ansible-role-jenkins-swarm-client
