---
- name: Converge
  hosts: all
  vars:
    jenkins_config_group: "jgroup"
    jenkins_config_owner: "juser"
    jenkins_master_url: "http://127.0.0.1:8080"
    jenkins_node_extra_labels: "extra-label"
    jenkins_node_label: "node-label"
    jenkins_node_name: "molecule-test-node"
    jenkins_node_packages:
      cowsay:
    jenkins_node_pool: "test"
    jenkins_swarm_extra_args:
      - "-e"
      - "FOO=BAR"
    jenkins_swarm_home: "/jenkins"
  roles:
    - role: ableton.jenkins_swarm_client
