---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-jenkins-swarm-client-jammy
    image: ubuntu:22.04
    privileged: true
  - name: ansible-role-jenkins-swarm-client-noble
    image: ubuntu:24.04
    privileged: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
