---
- name: Ensure daemon is installed
  become: true
  ansible.builtin.apt:
    name: "daemon"
    state: present

- name: Generate SysVinit launcher script
  become: true
  ansible.builtin.template:
    src: "jenkins-swarm-client-sysvinit.sh.j2"
    dest: "/etc/init.d/jenkins-swarm-client"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Install SysVinit service
  become: true
  ansible.builtin.sysvinit:
    name: "jenkins-swarm-client"
    enabled: true
    state: stopped
