---
- name: Assemble full command arguments
  set_fact:
    jenkins_swarm_full_args: "{{ jenkins_swarm_args + jenkins_swarm_extra_args }}"

- name: Ensure systemd service file exists
  become: true
  template:
    src: "jenkins-swarm-client.service.j2"
    dest: "/etc/systemd/system/jenkins-swarm-client.service"
    mode: "0644"

- name: Ensure systemd service runs at boot
  become: true
  systemd:
    name: jenkins-swarm-client
    enabled: true
    daemon_reload: true
    no_block: true
    state: stopped
