---
- name: Ensure service is stopped
  become: true
  ansible.builtin.service:
    enabled: false
    name: jenkins-swarm-client
    state: stopped
    # This normally isn't required, but we also test this role in Docker containers that
    # resemble standalone hosts with SSH. Since OpenSSH has libsystemd as a dependency,
    # it will fool the service module into selecting systemd as the service backend.
    use: "{{ ansible_service_mgr }}"
  ignore_errors: true  # noqa ignore-errors
  changed_when:
    - service_stopped.changed
    - is_molecule is not defined
  register: service_stopped
