---
- name: Create Jenkins Swarm user
  win_user:
    name: "{{ jenkins_config_owner }}"
    password: "{{ jenkins_user_password }}"
    state: present
    password_expired: false
    password_never_expires: true
    update_password: on_create

- name: Ensure Jenkins Swarm Client home directory exists
  become: true
  become_user: "{{ jenkins_config_owner }}"  # noqa 501
  win_file:
    path: "C:\\Users\\{{ jenkins_config_owner }}"
    state: directory
