---
- name: Include platform-specific defaults
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Ensure Jenkins working directory exists
  ansible.windows.win_file:
    path: "{{ jenkins_swarm_home }}"
    state: directory

- name: Download Swarm Client JAR
  ansible.windows.win_get_url:
    url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client\
      /{{ jenkins_swarm_client_version }}\
      /swarm-client-{{ jenkins_swarm_client_version }}.jar"
    dest: "{{ jenkins_swarm_jar_path }}"

- name: Copy logging properties file
  ansible.windows.win_copy:
    src: "logging.properties"
    dest: "{{ jenkins_swarm_logging_properties }}"

- name: Copy configuration file
  ansible.windows.win_template:
    src: "swarm-client-config.yml.j2"
    dest: "{{ jenkins_swarm_home }}\\swarm-client-config.yml"

- name: Add firewall exception for prometheus port
  community.windows.win_firewall_rule:
    name: "Jenkins Swarm Client Prometheus"
    localport: "{{ jenkins_swarm_prometheus_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  # Ansible treats templated variables as strings
  when: jenkins_swarm_prometheus_port != "-1"

- name: Get absolute path to Java executable
  ansible.windows.win_shell: >-
    Get-Command {{ java_exe }} | Select-Object 'Source' | Format-Wide -AutoSize
  changed_when: false
  register: get_command_java

- name: Include task file for Windows service start type
  ansible.builtin.include_tasks:
    file: "tasks/windows/install-{{ swarm_client_windows_start_type }}.yml"
