---
- name: Include platform-specific defaults
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Run user setup tasks
  include_tasks: "{{ role_path }}/tasks/windows/add-jenkins-user.yml"

- name: Check if reboot is necessary
  set_fact:
    chocolatey_reboot_necessary: false

- name: Ensure chocolatey is installed
  win_chocolatey:
    name: chocolatey
    state: present

- name: Install Chocolatey packages
  win_chocolatey:
    name: "{{ item.key }}"
    install_args: "{{ item.value.install_args | default('') }}"
    params: "{{ item.value.params | default('') }}"
    allow_prerelease: "{{ item.value.allow_prerelease | default(false) }}"
    version: "{{ item.value.version | default('') }}"
    state: present
  with_dict: "{{ jenkins_node_packages }}"
  register: chocolatey_result
  # Error code 3010 means that a reboot is necessary following installation of the
  # package.
  failed_when: >
    chocolatey_result.rc is defined and
    chocolatey_result.rc != 0 and
    chocolatey_result.rc != 3010

- name: Check if reboot is necessary
  set_fact:
    chocolatey_reboot_necessary: true
  when: item.rc is defined and item.rc == 3010
  with_items: "{{ chocolatey_result.results }}"

# Sometimes changes to the PATH made by chocolatey package installations don't seem to
# take effect until reboot.
- name: Reboot if packages were installed
  set_fact:
    chocolatey_reboot_necessary: true
  when: chocolatey_result is changed

- name: Reboot Windows host
  win_reboot:
    post_reboot_delay: 5
  when: chocolatey_reboot_necessary

- name: Ensure Jenkins working directory exists
  win_file:
    path: "{{ jenkins_swarm_home }}"
    state: directory

- name: Write labels to file
  win_template:
    src: "{{ role_path }}/templates/labels.txt.j2"
    dest: "{{ jenkins_swarm_labels_file }}"

- name: Download Swarm Client JAR
  win_get_url:
    url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client\
      /{{ jenkins_swarm_client_version }}\
      /swarm-client-{{ jenkins_swarm_client_version }}.jar"
    dest: "{{ jenkins_swarm_jar_path }}"

- name: Copy logging properties file
  win_copy:
    src: "{{ role_path }}/files/logging.properties"
    dest: "{{ jenkins_swarm_logging_properties }}"

- name: Add firewall exception for prometheus port
  community.windows.win_firewall_rule:
    name: "Jenkins Swarm Client Prometheus"
    localport: "{{ jenkins_swarm_prometheus_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  # Ansible treats templated variables as strings
  when: jenkins_swarm_prometheus_port != "-1"

- name: Assemble full command arguments
  set_fact:
    jenkins_swarm_full_args: "{{ jenkins_swarm_args + jenkins_swarm_extra_args }}"

- name: Get absolute path to Java executable
  win_shell:  "Get-Command {{ java_exe }} | Select-Object 'Source' | \
    Format-Wide -AutoSize"
  changed_when: false
  register: get_command_java

- include_tasks: "tasks/windows/install-{{ swarm_client_windows_start_type }}.yml"
