---
# It is necessary for us to remove and re-create this service since NSSM will fail with an
# error when creating the service if it already exists. This could be mitigated by adding
# "ignore_errors: true" to the service creation step, but I would prefer to recreate the
# service rather than suppress any errors which may occur while creating it. Also, we need
# to make sure that if the arguments in jenkins_swarm_cmd change then they are added to
# the NSSM service.
- name: Remove Windows service
  ansible.windows.win_service:
    name: "{{ jenkins_swarm_service_name }}"
    state: absent
  ignore_errors: true  # noqa ignore-errors

- name: Create Windows service with NSSM
  community.windows.win_nssm:
    name: "{{ jenkins_swarm_service_name }}"
    application: "{{ get_command_java.stdout | trim }}"
    arguments: "{{ jenkins_swarm_launch_args }}"
    description: "{{ jenkins_swarm_service_description }}"
    working_directory: "{{ jenkins_swarm_home }}"
    username: "{{ jenkins_config_owner }}"
    password: "{{ jenkins_user_password }}"
    stderr_file: "jenkins-swarm-client.stderr.log"
    stdout_file: "jenkins-swarm-client.stdout.log"
    state: stopped

- name: Ensure that Jenkins user can run services
  ansible.windows.win_user_right:
    name: "SeServiceLogonRight"
    action: add
    users:
      - "{{ jenkins_config_owner }}"
