---
- name: Include platform-specific defaults
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Start Windows service
  win_service:
    name: "{{ jenkins_swarm_service_name }}"
    start_mode: auto
    state: started
