---
- name: Include default variables
  include_vars: "{{ role_path }}/defaults/{{ ansible_os_family | lower }}.yml"

# TODO: This might not be necessary
# The idea here is to fix a JNLP4 warning that pops up in the Jenknis build
# logs, but even with this port opened, the warning still happens. =/
- name: Open port in Windows firewall
  win_shell: >
    New-NetFirewallRule \
      -DisplayName 'Jenkins Swarm Client' \
      -Profile @('Domain', 'Public') \
      -Direction Inbound \
      -Action Allow \
      -Protocol TCP \
      -LocalPort @({{ jenkins_swarm_port }})

- name: Copy swarm plugin client
  win_copy:
    src: "{{ role_path }}/files/{{ jenkins_swarm_jar }}"
    dest: "{{ jenkins_swarm_home }}\\{{ jenkins_swarm_jar }}"

- name: Copy NSSM
  win_copy:
    src: "{{ role_path }}/files/nssm.exe"
    dest: "{{ jenkins_swarm_home }}\\nssm.exe"

- name: Check if Windows service exists
  win_service:
    name: "{{ jenkins_swarm_service_name }}"
  register: win_service_info

- name: Remove Windows service
  win_service:
    name: "{{ jenkins_swarm_service_name }}"
    state: absent
  when: win_service_info.exists

- name: Create Windows service with NSSM
  win_shell: >
    {{ jenkins_swarm_home }}\\nssm.exe install \
      '{{ jenkins_swarm_service_name }}' \
      {{ jenkins_swarm_cmd }}

- name: Set service startup directory
  win_shell: >
    {{ jenkins_swarm_home }}\\nssm.exe set \
      '{{ jenkins_swarm_service_name }}' \
      AppDirectory  {{ jenkins_swarm_home }}

- name: Start Windows service
  win_service:
    name: "{{ jenkins_swarm_service_name }}"
    start_mode: auto
    state: started
