---
- name: Include platform-specific defaults
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Ensure Jenkins Swarm Client home directory exists
  become: true
  ansible.builtin.file:
    path: "{{ jenkins_swarm_home }}"
    state: directory
    mode: "0755"

- name: Ensure Jenkins Swarm group exists
  become: true
  ansible.builtin.group:
    name: "{{ jenkins_config_group }}"
    state: present

# On some Unix versions, we can run into trouble when trying to run usermod when a
# background task owned by the Jenkins user is running (specifically, on systems with
# newer versions of systemd running). For that reason we see if the user exists and then
# only create it if necessary.
# This means that the Jenkins user should *not* be created independently of Ansible,
# otherwise the other user attributes below will not be properly set.
- name: See whether Jenkins user exists
  ansible.builtin.command: "id -u {{ jenkins_config_owner }}"
  ignore_errors: true
  changed_when: false
  register: test_jenkins_user

- name: Create Jenkins Swarm user
  become: true
  ansible.builtin.user:
    name: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    home: "{{ jenkins_swarm_home }}"
    shell: "/bin/bash"
    state: present
  when: test_jenkins_user is failed

- name: Set correct ownership of Jenkins Swarm Client home directory
  become: true
  ansible.builtin.file:
    path: "{{ jenkins_swarm_home }}"
    state: directory
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    mode: "0755"
