---
- name: Create Jenkins swarm client launcher script
  become: true
  copy:
    dest: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
    mode: 0755
    content: |-
      #!/bin/sh
      {{ (jenkins_swarm_cmd + jenkins_swarm_extra_args) | join(" ") }} &

- name: Run swarm client launcher script
  become: true
  command: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
  async: 1
  changed_when: false
