---
- name: Assemble full command arguments
  set_fact:
    jenkins_swarm_full_args: "{{ jenkins_swarm_args + jenkins_swarm_extra_args }}"

- name: Create Jenkins swarm client launcher script
  become: true
  copy:
    dest: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
    mode: 0755
    content: |-
      #!/bin/sh
      {{ java_exe }} {{ jenkins_swarm_full_args | join(" ") }} &

- name: Run swarm client launcher script
  become: true
  command: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
  async: 1
  changed_when: false
