---
- name: Include default variables
  include_vars: "{{ role_path }}/defaults/{{ ansible_os_family | lower }}.yml"

- name: Create Jenkins working directory
  file:
    path: "{{ jenkins_swarm_home }}"
    state: directory

- name: Copy swarm plugin client
  copy:
    src: "{{ role_path }}/files/{{ jenkins_swarm_jar }}"
    dest: "{{ jenkins_swarm_home }}/{{ jenkins_swarm_jar }}"

- name: Create Jenkins swarm client launcher script
  copy:
    dest: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
    mode: 0755
    content: |
      #!/bin/sh
      {{ jenkins_swarm_cmd }} &

- name: Run swarm client launcher script
  shell: "{{ jenkins_swarm_home }}/swarm-client-launcher.sh"
  async: 1
